a = input("Enter something: ")
print(f"The primitive type is {type(a)}")
print("Spaces?",a.isspace())
print("Numeric?",a.isalnum())
print("Alphabetic?", a.isalpha())
print("Alphanumeric",a.isalnum())
print("uppercase?",a.isupper())
print("Lowercase?",a.islower())
print("Tittle?",a.istitle())